name: Build and generate docs

on:
    push:
        branches-ignore:
            - docs
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-package: jdk
                  java-version: 1.8

            - name: Build using Gradle
              run: |
                  chmod +x gradlew
                  ./gradlew build

            - name: Extract branch name
              id: extract_branch
              if: github.event_name == 'push'
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

            - name: Deploy documentation
              if: github.event_name == 'push'
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build/dokka/html
                  publish_branch: docs/${{ steps.extract_branch.outputs.branch }}
                  force_orphan: true
